
sudo: required
language: java

jdk:
  - openjdk8

script:
  - ./gradlew build -x test

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/rafaresearch/RxJava/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-a40a4130edcdadc2340da5787ca30353018173f2
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            